#!/bin/bash
# Create the epub 

OUTPUT_DIR=$1
EPUB_FILENAME=$2
VERSES=$3

FILE_EXTENSION="xhtml"
NAV_TEMPLATE="nav_template_epub.xhtml"
CONTENT_TEMPLATE="epub_content_template.opf"
EPUB_PATH="/var/www/alwaysrejoice/isilo"
EPUB=$EPUB_PATH/$EPUB_FILENAME

echo "Begin creating $OUTPUT_DIR\n"

#Remove the original file
rm -f $EPUB

python generate_hymn_verse.py $OUTPUT_DIR $VERSES $FILE_EXTENSION

python generate_nav.py "$OUTPUT_DIR/nav" $NAV_TEMPLATE $FILE_EXTENSION

echo "Copying all the shared files"
cp -R epub/shared/* $OUTPUT_DIR

echo "Creating the content.opf file"
python generate_epub_controls.py $OUTPUT_DIR $CONTENT_TEMPLATE

echo "Creating the epub zip file :$EPUB"
cd $OUTPUT_DIR
zip -X0q $EPUB mimetype
zip -Xur9Dq $EPUB *
cd -

echo "Validating $EPUB"
cd epub/epub_check
java -jar epubcheck-3.0.2-SNAPSHOT.jar $EPUB 2>&1 | tee -a output
cd -

echo "Done creating $EPUB"

