#!/usr/bin/env python
# Cleans up the HTML generated by the pdf->html program. 
# There are lots of messy HTML tags, and triplicate data
# After this is run, some manual cleanup is required - Choruses are not pulled out of the stanza in particular
import re
from db_functions import *


def stripTags(inStr):
  out = inStr.replace("<br>","").replace("<i>","").replace("</i>","").replace("<hr>", "")
  out = out.replace("&amp;","&").replace("&quot;","\"")
  return out


#Open the sonbook text file 
file = open("songbook/songbook_data.html","r")

#Stores the last X lines in order to remove duplicates
LASTLINE_COUNT = 3
lastLines = range(LASTLINE_COUNT)
lastIndex = -1
songbook_number = 0

for lineHtml in file.readlines():
  line = stripTags(lineHtml)
  #If this is a duplicate line, then ignore it
  if line in lastLines: continue
  
  #Ignore blank lines
  if (line.strip() == ""): continue
  if (line.strip() == "-"): continue
  
  #Ignore lines with just chords 
  if (re.match("^[ABCDEFGmajdimM12345679\#b \-\(\)]*$", line)): 
    if (re.match(".*[ABCDEFG].*", line)):  #Any line with just some numbers, or symbols is not a chord-match
      continue
  
  #Ignore page breaks 
  if (re.match("^-[0-9 ]*-$", line)): continue
  if (re.match("^\(continued\)$", line)): continue
  
  #Ignore anchor tags, put in for pagination purposes
  if (re.match("^<[aA] name=[0-9]*></[aA]>.*$", line)):
    continue
  
 
 #Store the line, which is used to remove duplicate lines
  lastLines[lastIndex] = line
  lastIndex += 1
  if (lastIndex >= LASTLINE_COUNT): lastIndex = 0

 # Special display lines, start of new hymn, start of stanza
 #It's just a number, then it's probably the songbook number 
  if (re.match("^[0-9]{1,4}$", line)):
    print "\n\nCalgary Songbook :"+line
    continue
  else: 
    # Check if there is a number at the start of the line, then it's probably a stanza number
    stanzaMatch = re.match("^([1-9]{1}) *(.*)$", line)
    if (stanzaMatch) : 
      chorusNum = str(stanzaMatch.group(1))
      lineText = str(stanzaMatch.group(2))
      print "\n" + chorusNum + "\n"+ lineText
      continue
  
#Display the line
  print line,
