language: python

python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "pypy"


script: nosetests

after_success:
  - pip install pep8 pyflakes
  - pep8 twitter/*.py
  - pyflakes twitter/*.py
  - pep8 tests/*.py
  - pyflakes tests/*.py

matrix:
  allow_failures:
    - python: "pypy"
